### ISSUE TITLE
specification what exactly he wants from us ..

### ISSUE THREAD

**Issue by ttomkk** [MarkSeliverstov/NSWI041-intro-to-software-engineering#10]
## According to the online lecture we should do several things

- [ ] **create use case diagram**

- this should be one UML diagram with use cases (their names) and actors (who is able to perform that particular task)
- it should be this part in the template: _[Document here all use cases. Create a subsection for each use case diagram. If you have only one use case diagram, you do not need a special subsection.]_

- [ ] **define use case scenarios**
- detailed interaction with the system (precondition, happy path, what can go wrong, postcondition)
- can be a list of steps (should be sufficient) or an activity diagram
- it should be this part in the template: _[Use case description in the structure from the lecture.]_

- [ ] **choose the most complex use case and express it as an activity diagram**
- it should be this part in the template: _[Add an activity diagram for one use case per a team member]_

did I misunderstand something ?

**Comment by MarkSeliverstov** [comment]
Hi, I have created kanban project for us where we can easily track tasks and turn them into issues - [link](https://github.com/users/MarkSeliverstov/projects/3). I think this kanban board will help us to track progress and plan tasks much better and more conveniently.

Also I have moved your [backlog.md](https://github.com/MarkSeliverstov/NSWI041-intro-to-software-engineering/blob/klimo-update/backlog.md) to this project, don't be afraid to change it :)

FYI @Coelurus @Senya-P @boba-buba @ttomkk
